export class AnomalyDefinition {
	name: string;
	short: string;
	tag: string;
	block: string;
	whClass: WhClass;
	data: boolean;
	relic: boolean;
	basePrice: number;
	priceWithAdditionalShips: number;
	hasAdditionalRats: boolean;
	hasDrifter: boolean;

	constructor(name: string,
		short: string,
		tag: string,
		block: string,
		whClass: WhClass,
		data: boolean,
		relic: boolean,
		basePrice: number,
		priceWithAdditionalShips: number,
		hasAdditionalRats: boolean,
		hasDrifter: boolean) {
		this.name = name;
		this.short = short;
		this.tag = tag;
		this.block = block;
		this.whClass = whClass;
		this.data = data;
		this.relic = relic;
		this.basePrice = basePrice;
		this.priceWithAdditionalShips = priceWithAdditionalShips;
		this.hasAdditionalRats = hasAdditionalRats;
		this.hasDrifter = hasDrifter;
	}
}

export enum WhClass {
	Unclassified,
	C1,
	C2,
	C3,
	C4,
	C5,
	C6
}

type Block = {
	text: string;
	color: string;
};

export const Blocks: Block[] = [
	{ text: "C5", color: "#e9fae6" },
	{ text: "C5 Data", color: "#faedf0" },
	{ text: "C5 Relic", color: "#edfafa" },
	{ text: "C3", color: "#faedf4" },
	{ text: "C3 Data", color: "#f5faed" },
	{ text: "C3 Relic", color: "#faf4ed" },
	{ text: "C4", color: "#e8ffee" },
	{ text: "C6", color: "#edfafa" },
	{ text: "other", color: "white" },
];

const AnomalyDefinitons: Map<string, AnomalyDefinition> = new Map([
	[
		"5CG",
		{
			name: "Core Garrison",
			short: "CG",
			tag: ".CG-",
			block: "C5",
			whClass: WhClass.C5,
			data: false,
			relic: false,
			basePrice: 253400000,
			priceWithAdditionalShips: 253400000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"5CS",
		{
			name: "Core Stronghold",
			short: "ST",
			tag: ".ST-",
			block: "C5",
			whClass: WhClass.C5,
			data: false,
			relic: false,
			basePrice: 234900000,
			priceWithAdditionalShips: 234900000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"5OO",
		{
			name: "Oruze Osobnyk",
			short: "OO",
			tag: ".OO-",
			block: "C5",
			whClass: WhClass.C5,
			data: false,
			relic: false,
			basePrice: 148800000,
			priceWithAdditionalShips: 164700000,
			hasAdditionalRats: true,
			hasDrifter: true,
		},
	],
	[
		"5QA",
		{
			name: "Quarantine Area",
			short: "QA",
			tag: ".QA-",
			block: "C5",
			whClass: WhClass.C5,
			data: false,
			relic: false,
			basePrice: 146900000,
			priceWithAdditionalShips: 146900000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"3FFS",
		{
			name: "Fortification Frontier Stronghold",
			short: "FFS",
			tag: "3FFS-",
			block: "C3",
			whClass: WhClass.C3,
			data: false,
			relic: false,
			basePrice: 41000000,
			priceWithAdditionalShips: 41000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3OFS",
		{
			name: "Outpost Frontier Stronghold",
			short: "OFS",
			tag: "3OFS-",
			block: "C3",
			whClass: WhClass.C3,
			data: false,
			relic: false,
			basePrice: 45100000,
			priceWithAdditionalShips: 45100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3SC",
		{
			name: "Solar Cell",
			short: "SC",
			tag: "3SC-",
			block: "C3",
			whClass: WhClass.C3,
			data: false,
			relic: false,
			basePrice: 47300000,
			priceWithAdditionalShips: 52300000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"3OC",
		{
			name: "The Oruze Construct",
			short: "OC",
			tag: "3OC-",
			block: "C3",
			whClass: WhClass.C3,
			data: false,
			relic: false,
			basePrice: 41600000,
			priceWithAdditionalShips: 44500000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"3R-FFQO",
		{
			name: "Forgotten Frontier Quarantine Outpost",
			short: "QO",
			tag: "3R-FFQO-",
			block: "C3 Relic",
			whClass: WhClass.C3,
			data: false,
			relic: true,
			basePrice: 76500000,
			priceWithAdditionalShips: 76500000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3R-FFRD",
		{
			name: "Forgotten Frontier Recursive Depot",
			short: "RD",
			tag: "3R-FFRD-",
			block: "C3 Relic",
			whClass: WhClass.C3,
			data: false,
			relic: true,
			basePrice: 92500000,
			priceWithAdditionalShips: 92500000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3D-UFD",
		{
			name: "Unsecured Frontier Database",
			short: "FD",
			tag: "3D-UFD-",
			block: "C3 Data",
			whClass: WhClass.C3,
			data: true,
			relic: false,
			basePrice: 88400000,
			priceWithAdditionalShips: 88400000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3D-UFR",
		{
			name: "Unsecured Frontier Receiver",
			short: "FR",
			tag: "3D-UFR-",
			block: "C3 Data",
			whClass: WhClass.C3,
			data: true,
			relic: false,
			basePrice: 75100000,
			priceWithAdditionalShips: 75100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"Drifter",
		{
			name: "drifter",
			short: "D",
			tag: "D-",
			block: "other",
			whClass: WhClass.Unclassified,
			data: false,
			relic: false,
			basePrice: 300000000,
			priceWithAdditionalShips: 300000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"Drifter-Recon",
		{
			name: "minidrifter",
			short: "RD",
			tag: "MD-",
			block: "other",
			whClass: WhClass.Unclassified,
			data: false,
			relic: false,
			basePrice: 100000000,
			priceWithAdditionalShips: 100000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5CEW",
		{
			name: "upg_c5",
			short: "Upg",
			tag: "5CEW-",
			block: "other",
			whClass: WhClass.C5,
			data: false,
			relic: false,
			basePrice: 105000000,
			priceWithAdditionalShips: 105000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"6CEW",
		{
			name: "upg_c6",
			short: "Upg",
			tag: "6CEW-",
			block: "other",
			whClass: WhClass.C6,
			data: false,
			relic: false,
			basePrice: 140000000,
			priceWithAdditionalShips: 140000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"6CC",
		{
			name: "Core Citadel",
			short: "CS",
			tag: ".CC-",
			block: "C6",
			whClass: WhClass.C6,
			data: false,
			relic: false,
			basePrice: 310100000,
			priceWithAdditionalShips: 310100000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"6CB",
		{
			name: "Core Bastion",
			short: "CB",
			tag: ".CB-",
			block: "C6",
			whClass: WhClass.C6,
			data: false,
			relic: false,
			basePrice: 445600000,
			priceWithAdditionalShips: 445600000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"6SER",
		{
			name: "Strange Energy Readings",
			short: "SER",
			tag: ".SER-",
			block: "C6",
			whClass: WhClass.C6,
			data: false,
			relic: false,
			basePrice: 260000000,
			priceWithAdditionalShips: 291800000,
			hasAdditionalRats: true,
			hasDrifter: true,
		},
	],
	[
		"6TM",
		{
			name: "The Mirror",
			short: "TM",
			tag: ".TM-",
			block: "C6",
			whClass: WhClass.C6,
			data: false,
			relic: false,
			basePrice: 363200000,
			priceWithAdditionalShips: 363200000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5R-FCDF",
		{
			name: "Forgotten Core Data Field",
			short: "DF",
			tag: "5R-FCDF-",
			block: "C5 Relic",
			whClass: WhClass.C5,
			data: false,
			relic: true,
			basePrice: 279000000,
			priceWithAdditionalShips: 279000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5R-FCIP",
		{
			name: "Forgotten Core Information Pen",
			short: "IP",
			tag: "5R-FCIP-",
			block: "C5 Relic",
			whClass: WhClass.C5,
			data: false,
			relic: true,
			basePrice: 332900000,
			priceWithAdditionalShips: 348800000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"5D-UFER",
		{
			name: "Unsecured Frontier Enclave Relay",
			short: "ER",
			tag: "5D-UFER-",
			block: "C5 Data",
			whClass: WhClass.C5,
			data: true,
			relic: false,
			basePrice: 314000000,
			priceWithAdditionalShips: 329900000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"5D-UFSB",
		{
			name: "Unsecured Frontier Server Bank",
			short: "SB",
			tag: "5D-UFSB-",
			block: "C5 Data",
			whClass: WhClass.C5,
			data: true,
			relic: false,
			basePrice: 272100000,
			priceWithAdditionalShips: 272100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4FB",
		{
			name: "Frontier Barracks",
			short: "FB",
			tag: "4FB-",
			block: "C4",
			whClass: WhClass.C4,
			data: false,
			relic: false,
			basePrice: 86700000,
			priceWithAdditionalShips: 86700000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4FCP",
		{
			name: "Frontier Command Post",
			short: "FCP",
			tag: "4FCP-",
			block: "C4",
			whClass: WhClass.C4,
			data: false,
			relic: false,
			basePrice: 92300000,
			priceWithAdditionalShips: 92300000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4IT",
		{
			name: "Integrated Terminus",
			short: "IT",
			tag: "4IT-",
			block: "C4",
			whClass: WhClass.C4,
			data: false,
			relic: false,
			basePrice: 56800000,
			priceWithAdditionalShips: 56800000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4SIS",
		{
			name: "Sleeper Information Sanctum",
			short: "SIS",
			tag: "4SIS-",
			block: "C4",
			whClass: WhClass.C4,
			data: false,
			relic: false,
			basePrice: 80300000,
			priceWithAdditionalShips: 86100000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
]);

export default AnomalyDefinitons;
