export class AnomalyDefinition {
	name: string;
	short: string;
	tag: string;
	whClasses: WhClass[];
	data: boolean;
	relic: boolean;
	notAnom: boolean;
	basePrice: number;
	priceWithAdditionalShips: number;
	hasAdditionalRats: boolean;
	hasDrifter: boolean;

	constructor(name: string,
		short: string,
		tag: string,
		whClasses: WhClass[],
		data: boolean,
		relic: boolean,
		notAnom: boolean,
		basePrice: number,
		priceWithAdditionalShips: number,
		hasAdditionalRats: boolean,
		hasDrifter: boolean) {
		this.name = name;
		this.short = short;
		this.tag = tag;
		this.whClasses = whClasses;
		this.data = data;
		this.relic = relic;
		this.notAnom = notAnom;
		this.basePrice = basePrice;
		this.priceWithAdditionalShips = priceWithAdditionalShips;
		this.hasAdditionalRats = hasAdditionalRats;
		this.hasDrifter = hasDrifter;
	}
}

export enum WhClass {
	Unclassified,
	C1,
	C2,
	C3,
	C4,
	C5,
	C6
}

const AnomalyDefinitons: Map<string, AnomalyDefinition> = new Map([
	[
		"5CG",
		{
			name: "Core Garrison",
			short: "CG",
			tag: ".CG-",
			whClasses: [WhClass.C5],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 253400000,
			priceWithAdditionalShips: 253400000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"5CS",
		{
			name: "Core Stronghold",
			short: "ST",
			tag: ".ST-",
			whClasses: [WhClass.C5],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 234900000,
			priceWithAdditionalShips: 234900000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"5OO",
		{
			name: "Oruze Osobnyk",
			short: "OO",
			tag: ".OO-",
			whClasses: [WhClass.C5],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 148800000,
			priceWithAdditionalShips: 164700000,
			hasAdditionalRats: true,
			hasDrifter: true,
		},
	],
	[
		"5QA",
		{
			name: "Quarantine Area",
			short: "QA",
			tag: ".QA-",
			whClasses: [WhClass.C5],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 146900000,
			priceWithAdditionalShips: 146900000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"3FFS",
		{
			name: "Fortification Frontier Stronghold",
			short: "FFS",
			tag: "3FFS-",
			whClasses: [WhClass.C3],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 41000000,
			priceWithAdditionalShips: 41000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3OFS",
		{
			name: "Outpost Frontier Stronghold",
			short: "OFS",
			tag: "3OFS-",
			whClasses: [WhClass.C3],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 45100000,
			priceWithAdditionalShips: 45100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3SC",
		{
			name: "Solar Cell",
			short: "SC",
			tag: "3SC-",
			whClasses: [WhClass.C3],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 47300000,
			priceWithAdditionalShips: 52300000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"3OC",
		{
			name: "The Oruze Construct",
			short: "OC",
			tag: "3OC-",
			whClasses: [WhClass.C3],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 41600000,
			priceWithAdditionalShips: 44500000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"3R-FFQO",
		{
			name: "Forgotten Frontier Quarantine Outpost",
			short: "QO",
			tag: "3R-FFQO-",
			whClasses: [WhClass.C3],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 76500000,
			priceWithAdditionalShips: 76500000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3R-FFRD",
		{
			name: "Forgotten Frontier Recursive Depot",
			short: "RD",
			tag: "3R-FFRD-",
			whClasses: [WhClass.C3],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 92500000,
			priceWithAdditionalShips: 92500000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3D-UFD",
		{
			name: "Unsecured Frontier Database",
			short: "FD",
			tag: "3D-UFD-",
			whClasses: [WhClass.C3],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 88400000,
			priceWithAdditionalShips: 88400000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"3D-UFR",
		{
			name: "Unsecured Frontier Receiver",
			short: "FR",
			tag: "3D-UFR-",
			whClasses: [WhClass.C3],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 75100000,
			priceWithAdditionalShips: 75100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"Drifter",
		{
			name: "drifter",
			short: "D",
			tag: "D-",
			whClasses: [WhClass.C5, WhClass.C6],
			data: false,
			relic: false,
			notAnom: true,
			basePrice: 300000000,
			priceWithAdditionalShips: 300000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"Drifter-Recon",
		{
			name: "minidrifter",
			short: "RD",
			tag: "MD-",
			whClasses: [WhClass.C5, WhClass.C6],
			data: false,
			relic: false,
			notAnom: true,
			basePrice: 100000000,
			priceWithAdditionalShips: 100000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5CEW",
		{
			name: "upg_c5",
			short: "Upg",
			tag: "5CEW-",
			whClasses: [WhClass.C5],
			data: false,
			relic: false,
			notAnom: true,
			basePrice: 105000000,
			priceWithAdditionalShips: 105000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"6CEW",
		{
			name: "upg_c6",
			short: "Upg",
			tag: "6CEW-",
			whClasses: [WhClass.C6],
			data: false,
			relic: false,
			notAnom: true,
			basePrice: 140000000,
			priceWithAdditionalShips: 140000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"6CC",
		{
			name: "Core Citadel",
			short: "CS",
			tag: ".CC-",
			whClasses: [WhClass.C6],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 310100000,
			priceWithAdditionalShips: 310100000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"6CB",
		{
			name: "Core Bastion",
			short: "CB",
			tag: ".CB-",
			whClasses: [WhClass.C6],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 445600000,
			priceWithAdditionalShips: 445600000,
			hasAdditionalRats: false,
			hasDrifter: true,
		},
	],
	[
		"6SER",
		{
			name: "Strange Energy Readings",
			short: "SER",
			tag: ".SER-",
			whClasses: [WhClass.C6],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 260000000,
			priceWithAdditionalShips: 291800000,
			hasAdditionalRats: true,
			hasDrifter: true,
		},
	],
	[
		"6TM",
		{
			name: "The Mirror",
			short: "TM",
			tag: ".TM-",
			whClasses: [WhClass.C6],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 363200000,
			priceWithAdditionalShips: 363200000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5R-FCDF",
		{
			name: "Forgotten Core Data Field",
			short: "DF",
			tag: "5R-FCDF-",
			whClasses: [WhClass.C5],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 279000000,
			priceWithAdditionalShips: 279000000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"5R-FCIP",
		{
			name: "Forgotten Core Information Pen",
			short: "IP",
			tag: "5R-FCIP-",
			whClasses: [WhClass.C5],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 332900000,
			priceWithAdditionalShips: 348800000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"5D-UFER",
		{
			name: "Unsecured Frontier Enclave Relay",
			short: "ER",
			tag: "5D-UFER-",
			whClasses: [WhClass.C5],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 314000000,
			priceWithAdditionalShips: 329900000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"5D-UFSB",
		{
			name: "Unsecured Frontier Server Bank",
			short: "SB",
			tag: "5D-UFSB-",
			whClasses: [WhClass.C5],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 272100000,
			priceWithAdditionalShips: 272100000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4FB",
		{
			name: "Frontier Barracks",
			short: "FB",
			tag: "4FB-",
			whClasses: [WhClass.C4],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 86700000,
			priceWithAdditionalShips: 86700000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4FCP",
		{
			name: "Frontier Command Post",
			short: "FCP",
			tag: "4FCP-",
			whClasses: [WhClass.C4],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 92300000,
			priceWithAdditionalShips: 92300000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4IT",
		{
			name: "Integrated Terminus",
			short: "IT",
			tag: "4IT-",
			whClasses: [WhClass.C4],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 56800000,
			priceWithAdditionalShips: 56800000,
			hasAdditionalRats: false,
			hasDrifter: false,
		},
	],
	[
		"4SIS",
		{
			name: "Sleeper Information Sanctum",
			short: "SIS",
			tag: "4SIS-",
			whClasses: [WhClass.C4],
			data: false,
			relic: false,
			notAnom: false,
			basePrice: 80300000,
			priceWithAdditionalShips: 86100000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"4R-FFCM",
		{
			name: "Forgotten Frontier Conversion Module",
			short: "CM",
			tag: "4R-FFCM-",
			whClasses: [WhClass.C4],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 134100000,
			priceWithAdditionalShips: 146500000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"4R-FFEC",
		{
			name: "Forgotten Frontier Evacuation Center",
			short: "EC",
			tag: "4R-FFEC-",
			whClasses: [WhClass.C4],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 82300000,
			priceWithAdditionalShips: 91600000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"4D-UFDN",
		{
			name: "Unsecured Frontier Digital Nexus",
			short: "DN",
			tag: "4D-UFDN-",
			whClasses: [WhClass.C4],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 117700000,
			priceWithAdditionalShips: 130100000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"4D-UFTH",
		{
			name: "Unsecured Frontier Trinary Hub",
			short: "TH",
			tag: "4D-UFTH-",
			whClasses: [WhClass.C4],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 82300000,
			priceWithAdditionalShips: 91600000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"6R-FCAH",
		{
			name: "Forgotten Core Assembly Hall",
			short: "AH",
			tag: "6R-FCAH-",
			whClasses: [WhClass.C6],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 621600000,
			priceWithAdditionalShips: 642500000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"6R-FCCD",
		{
			name: "Forgotten Core Circuitry Disassembler",
			short: "CD",
			tag: "6R-FCCD-",
			whClasses: [WhClass.C6],
			data: false,
			relic: true,
			notAnom: false,
			basePrice: 636700000,
			priceWithAdditionalShips: 657600000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"6D-UCBA",
		{
			name: "Unsecured Core Backup Array",
			short: "BA",
			tag: "6R-UCBA-",
			whClasses: [WhClass.C6],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 667400000,
			priceWithAdditionalShips: 688300000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
	[
		"6D-UCE",
		{
			name: "Unsecured Core Emergence",
			short: "E",
			tag: "6R-UCE-",
			whClasses: [WhClass.C6],
			data: true,
			relic: false,
			notAnom: false,
			basePrice: 606200000,
			priceWithAdditionalShips: 627100000,
			hasAdditionalRats: true,
			hasDrifter: false,
		},
	],
]);

export default AnomalyDefinitons;
